### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by AtengChen** [TomJGooding/textual-dino#9]
### Is there an existing issue for this?

- [x] I have searched the open issues

### Description of the bug

When I tries to run the source in the file dino.py, an error ocurred:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[56], line 271
    267         self.tick.resume()
    270 if __name__ == "__main__":
--> 271     game = DinosaurGame()
    272     game.run(inline=True)

Cell In[56], line 198, in DinosaurGame.__init__(self)
    197 def __init__(self) -> None:
--> 198     super().__init__(ansi_color=True)
    199     self.game_over = False
    200     self.high_score: int = 0

TypeError: App.__init__() got an unexpected keyword argument 'ansi_color'
```

### To Reproduce

1. Open an IPython terminal.
2. Paste the contents of the file dino.py into the terminal.
3. Press enter to execute the contents.

### Expected behavior

The dino game should run without any errors.

### Screenshots

![error](https://github.com/user-attachments/assets/654fa193-e06c-4d1c-85b3-c114e34de71e)

**Comment by TomJGooding** [comment]
It sounds like you have Textual installed, but an older version than specified in [requirements.txt](https://github.com/TomJGooding/textual-dino/blob/main/requirements.txt)?

This was really only a toy project to experiment with Textual, so please don't set your expectations too high!
